---
- name: Configure Common Configuration Settings
  hosts: all
  gather_facts: false
  roles:
    - common

#- name: Add Chef Client
#  hosts:
#    - sample
#  gather_facts: false
#  roles:
#    - chefclient
