---
- name: Configure Common Configuration Settings
  hosts: centos
  gather_facts: false
  roles:
    - commoncentos

- name: Add Chef Client
  hosts: kubernetes
  gather_facts: false
  roles:
    - kubernetes
